name: CloudSim Multi-Tenant FaaS Scheduling Comparison

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

jobs:
  run-simulations:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v4

    - name: Set up JDK 8
      uses: actions/setup-java@v4
      with:
        java-version: '8'
        distribution: 'temurin'

    - name: Create lib directory
      run: mkdir -p lib

    - name: Copy CloudSim JAR to lib directory
      run: cp libs/cloudsim-3.0.3.jar lib/

    - name: Compile Java source files
      run: |
        mkdir -p bin
        javac -cp "lib/*" -d bin $(find src -name "*.java")

    - name: Run Multi-Tenant FaaS Scheduling Simulations
      run: |
        mkdir -p output
        java -cp "bin:lib/*" simulations.MultiTenantFaaS

    - name: Prepare Reports for Upload
      if: always()
      run: |
        mkdir -p safe_upload
        [ -f output/comparison_report.txt ] && cp output/comparison_report.txt safe_upload/
        [ -f output/multitenant_roundrobin.csv ] && cp output/multitenant_roundrobin.csv safe_upload/
        [ -f output/multitenant_sjf.csv ] && cp output/multitenant_sjf.csv safe_upload/

    - name: Upload Artifacts
      if: always()
      uses: actions/upload-artifact@v4
      with:
        name: simulation-reports
        path: safe_upload

    - name: Generate Summary
      if: always()
      run: |
        echo "## Multi-Tenant FaaS Scheduling Comparison Results" >> $GITHUB_STEP_SUMMARY
        echo "### Round Robin vs SJF Performance" >> $GITHUB_STEP_SUMMARY
        echo "Simulation completed using Java 1.8. Reports (if any) are uploaded." >> $GITHUB_STEP_SUMMARY
