name: Java CI for CloudSim Project

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v3

    - name: Set up JDK 8
      uses: actions/setup-java@v3
      with:
        java-version: '8'
        distribution: 'adopt'

    - name: Compile Java Files
      run: |
        mkdir -p bin
        javac -d bin -cp "lib/*" $(find src -name "*.java")

    - name: Run Simulation
      run: |
        mkdir -p output
        java -cp "bin:lib/*" simulations.MultiTenantFaaS

    - name: Upload Output Files
      uses: actions/upload-artifact@v3
      with:
        name: simulation-output
        path: output/
